### ISSUE TITLE
uninitialized value

### ISSUE THREAD

**Issue by MarcusCaepio** [lausser/check_ups_health#5]
Hi Gerhard,

just updated from 2.7.1 to 2.7.1.2
Now I got a short crtitcal alarm, which disappeared after a re-check.

[ 1/5 ] Use of uninitialized value in sprintf at /usr/lib/nagios/plugins/check_ups_health line 20051.

**Comment by lausser** [comment]
That would come from

sprintf 'capacity is %.2f%%', $self->{upsAdvBatteryCapacity}

Do you get a valid „capacity is ….%“ output now?

Gerhard

Von: MarcusCaepio [mailto:notifications@github.com]
Gesendet: Dienstag, 25. Oktober 2016 14:44
An: lausser/check_ups_health check_ups_health@noreply.github.com
Betreff: [lausser/check_ups_health] uninitialized value (#5)

Hi Gerhard,

just updated from 2.7.1 to 2.7.1.2
Now I got a short crtitcal alarm, which disappeared after a re-check.

[ 1/5 ] Use of uninitialized value in sprintf at 
/usr/lib/nagios/plugins/check_ups_health line 20051.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub 
https://github.com/lausser/check_ups_health/issues/5 , or mute the thread

**Comment by MarcusCaepio** [comment]
Yes, the capacity was correct before and after the short alert.
But because I never saw this alarm in the version before, I thought it could be fine to tell you about it :)

**Comment by MarcusCaepio** [comment]
Everything working fine :)
